{% set name = "gtabview" %}
{% set version = "0.10.1" %}
{% set sha256 = "a228fb066fea84537ff9b1ee4f558c635e1c5fd82aafd7e58a5bb9d9f55f6d64" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} setup.py install
  entry_points:
    - gtabview = gtabview_cli.gtabview:main

requirements:
  host:
    - python >=2.7
    - setuptools
  run:
    - python >=2.7
    - pyqt

test:
  imports:
    - gtabview
  commands:
    - gtabview -h

about:
  home: https://github.com/TabViewer/gtabview/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Simple graphical tabular data viewer
  description: |
    Simple tabular data viewer that can be used both stand-alone and as a
    Python module for various files and Python/Pandas/NumPy data structures.

extra:
  recipe-maintainers:
    - wavexx
